version: '2'
services:
  eureka:
    build:
      context: ./Spring-Eureka/
    ports: 
      - "8761:8761"
      
  zuul:
    build:
      context: ./Spring-Zuul
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    
  webapp:
    build: 
      context: ./button-click-Web-App
    ports:
      - "6001:6001"
    depends_on:
      - eureka
      
  
  writer:
    build:
      context: ./button-count-writer
    ports:
      - "7001:7001"
    depends_on:
      - eureka
   
  recorder:
    build:
      context: ./button-count-recorder
    ports:
      - "9001:9001"
    depends_on:
      - eureka
      - mongodb
   
  mongodb:
    image: mongo:latest
    command: mongod --noprealloc --smallfiles --dbpath /data/db --nojournal --oplogSize 16 --noauth
    ports:
      - "27017:27017"
    environment:
      TERM: xterm
    volumes:
      - /home/akhil/data/mongo:/data/db
      