version: '2'
services:
  eureka:
    image: eureka
    container_name: eureka
    ports: 
      - "8761:8761"
      
  zuul:
    image: zuul
    container_name: zuul
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    
  webapp:
    image: web-app
    ports:
      - "6001"
    depends_on:
      - eureka
  
  writer:
    image: writer
    ports:
      - "7001"
    depends_on:
      - eureka
   
  recorder:
    image: recorder
    ports:
      - "9001"
    depends_on:
      - eureka
      - mongodb
   
  mongodb:
    image: mongo:latest
    command: mongod --noprealloc --smallfiles --dbpath /data/db --nojournal --oplogSize 16 --noauth
    ports:
      - "27017:27017"
    environment:
      TERM: xterm
    volumes:
      - /home/vagrant/data/mongo:/data/db
      
