spring:
  application:
    name: button-click-Web-App

server:
  port: 6001
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

writer:
  ribbon:
    eureka:
      enabled: true
    DeploymentContextBasedVipAddresses: button-count-writer
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ServerListRefreshInterval: 15000